# Generated by Django 4.1 on 2022-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("nom_categorie", models.CharField(max_length=25)),
                ("nom_article", models.CharField(max_length=35)),
                ("description", models.CharField(max_length=65)),
                ("prix", models.FloatField(max_length=4)),
                ("image_path", models.CharField(default=None, max_length=255)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("nom_entreprise", models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie_article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_categorie_article", models.CharField(max_length=25)),
                ("id_user", models.IntegerField(default=None)),
                ("id_ets", models.IntegerField(default=None)),
                ("nom_entreprise", models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie_ets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_categorie_ets", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("nom_categorie_ets", models.CharField(max_length=25)),
                ("nom_ets", models.CharField(max_length=40)),
                ("logo_ets", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="social_media_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(default=None, max_length=255)),
                ("link", models.CharField(default=None, max_length=70)),
                ("id_user", models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="UserConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default=None, max_length=254)),
                ("code_confirmation", models.TextField(max_length=8)),
            ],
        ),
    ]
