# Generated by Django 4.1 on 2022-12-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="social_media_link",
        ),
    ]
