# Generated by Django 4.1 on 2022-12-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0004_social_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="social_media_link",
            name="link",
            field=models.CharField(default=None, max_length=80),
        ),
    ]
