# Generated by Django 4.1 on 2022-12-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0005_social_media_link_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="devise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_devise", models.CharField(default=None, max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name="entreprise",
            name="nom_devise",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
