# Generated by Django 4.1 on 2022-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0006_devise_entreprise_nom_devise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_devise", models.CharField(default=None, max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name="devise",
        ),
    ]
