# Generated by Django 4.1 on 2022-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0007_devises_delete_devise"),
    ]

    operations = [
        migrations.AddField(
            model_name="devises",
            name="symbole",
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name="devises",
            name="nom_devise",
            field=models.CharField(default=None, max_length=35),
        ),
    ]
