# Generated by Django 4.1 on 2022-12-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0008_devises_symbole_alter_devises_nom_devise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devises",
            name="symbole",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
