# Generated by Django 4.1 on 2022-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0009_alter_devises_symbole"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("flag_en_vigeur", models.IntegerField(default=None, max_length=2)),
                ("periodicite", models.IntegerField(default=None, max_length=2)),
                ("date_effet", models.DateTimeField(default=None)),
                ("date_fin", models.DateTimeField(default=None)),
            ],
        ),
    ]
