# Generated by Django 4.1 on 2022-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0011_user_qrcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_model",
            new_name="path_qrcode_design",
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="path_qrcode_initial",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
