# Generated by Django 4.1 on 2022-12-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0013_alter_article_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prix",
            field=models.FloatField(max_length=4),
        ),
    ]
