# Generated by Django 4.1 on 2023-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0014_alter_article_prix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_qrcode",
            name="qr_code_model",
            field=models.CharField(default=None, max_length=9),
        ),
    ]
