# Generated by Django 4.1 on 2023-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0015_user_qrcode_qr_code_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_qrcode",
            name="nom_entreprise",
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="id_entreprise",
            field=models.IntegerField(default=None),
        ),
    ]
