# Generated by Django 4.1 on 2023-01-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0016_remove_user_qrcode_nom_entreprise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_qrcode",
            name="url_redirect",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
