# Generated by Django 4.1 on 2023-01-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0017_user_qrcode_url_redirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_qrcode",
            name="personalise",
            field=models.IntegerField(default=None, max_length=1),
        ),
    ]
