# Generated by Django 4.1 on 2023-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0018_user_qrcode_personalise"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_qrcode_initial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("path", models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
