# Generated by Django 4.1 on 2023-01-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0019_user_qrcode_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="url_redirect",
            new_name="entreprise_url_redirect",
        ),
    ]
