# Generated by Django 4.1 on 2023-01-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_djaagou_scan",
            "0021_rename_entreprise_url_redirect_user_qrcode_url_redirection",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_qrcode_design",
            new_name="path_qrcode_design_modele1",
        ),
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_qrcode_initial",
            new_name="path_qrcode_design_modele2",
        ),
        migrations.RenameField(
            model_name="user_qrcode_initial",
            old_name="path",
            new_name="path_black",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="qr_code_model",
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="path_qrcode_design_modele3",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="path_qrcode_initial_black",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="path_qrcode_initial_white",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="user_qrcode_initial",
            name="path_white",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
