# Generated by Django 4.1 on 2023-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_djaagou_scan",
            "0022_rename_path_qrcode_design_user_qrcode_path_qrcode_design_modele1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_qrcode_design_modele1",
            new_name="path_qrcode_design",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="path_qrcode_design_modele2",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="path_qrcode_design_modele3",
        ),
        migrations.AddField(
            model_name="user_qrcode",
            name="libelle_modele",
            field=models.CharField(default=None, max_length=35),
        ),
    ]
