# Generated by Django 4.1 on 2023-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_djaagou_scan",
            "0023_rename_path_qrcode_design_modele1_user_qrcode_path_qrcode_design_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="statut",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="categorie_article",
            name="statut",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="statut",
            field=models.IntegerField(default=None),
        ),
    ]
