# Generated by Django 4.1 on 2023-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0024_article_statut_categorie_article_statut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="nb_places",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
