# Generated by Django 4.1 on 2023-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0025_entreprise_nb_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option_tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("numero_table", models.IntegerField(default=None)),
                ("staut_table", models.IntegerField(default=1)),
            ],
        ),
    ]
