# Generated by Django 4.1 on 2023-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0026_option_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_tables",
            name="nb_places",
            field=models.IntegerField(default=0),
        ),
    ]
