# Generated by Django 4.1 on 2023-01-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0027_option_tables_nb_places"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option_tables",
            old_name="staut_table",
            new_name="statut_table",
        ),
    ]
