# Generated by Django 4.1 on 2023-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0028_rename_staut_table_option_tables_statut_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_custom_flyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("name_modele", models.CharField(max_length=8)),
                ("path_modele", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="user_flyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("name_modele", models.CharField(max_length=8)),
                ("path_modele", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="User_qrcode_initial",
        ),
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_qrcode_design",
            new_name="path_black_qrcode",
        ),
        migrations.RenameField(
            model_name="user_qrcode",
            old_name="path_qrcode_initial_black",
            new_name="path_white_qrcode",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="libelle_modele",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="path_qrcode_initial_white",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="personalise",
        ),
        migrations.RemoveField(
            model_name="user_qrcode",
            name="url_redirection",
        ),
    ]
