# Generated by Django 4.1 on 2023-02-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0031_all_social_media_user_social_media_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise_social_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_logo", models.CharField(default=None, max_length=255)),
                ("name_reseau_social", models.CharField(max_length=25)),
                ("id_user", models.IntegerField(default=None)),
                ("link", models.CharField(default=None, max_length=80)),
                ("id_entreprise", models.IntegerField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name="user_social_media",
        ),
    ]
