# Generated by Django 4.1 on 2023-02-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0032_entreprise_social_media_delete_user_social_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise_social_media",
            old_name="name_reseau_social",
            new_name="name",
        ),
    ]
