# Generated by Django 4.1 on 2023-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0034_rename_name_reseau_social_all_social_media_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise_social_media",
            name="phone_number",
            field=models.IntegerField(default=None),
        ),
    ]
