# Generated by Django 4.1 on 2023-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0036_alter_entreprise_social_media_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise_social_media",
            name="phone_number",
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
