# Generated by Django 4.1 on 2023-02-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0039_option_commande_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option_commande",
            old_name="quantité",
            new_name="quantite",
        ),
        migrations.RenameField(
            model_name="option_commande_intermediaire",
            old_name="quantité",
            new_name="quantite",
        ),
    ]
