# Generated by Django 4.1 on 2023-02-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0040_rename_quantité_option_commande_quantite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option_commande_intermediaire",
            name="id_unknown_user",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
