# Generated by Django 4.1 on 2023-02-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0042_option_commande_intermediaire_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_commande_intermediaire",
            name="name",
            field=models.CharField(default=None, max_length=65),
        ),
    ]
