# Generated by Django 4.1 on 2023-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0043_option_commande_intermediaire_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_commande",
            name="numero_table",
            field=models.IntegerField(default=None),
        ),
    ]
