# Generated by Django 4.1 on 2023-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0044_option_commande_numero_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_commande_intermediaire",
            name="numero_table",
            field=models.IntegerField(default=None),
        ),
    ]
