# Generated by Django 4.1 on 2023-02-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0045_option_commande_intermediaire_numero_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option_commande_intermediaire",
            name="numero_table",
        ),
    ]
