# Generated by Django 4.1 on 2023-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0047_option_commande_custumer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_commande",
            name="id_commande",
            field=models.CharField(default=None, max_length=25),
        ),
    ]
