# Generated by Django 4.1 on 2023-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0048_option_commande_id_commande"),
    ]

    operations = [
        migrations.AddField(
            model_name="option_commande",
            name="statut",
            field=models.IntegerField(default=None),
        ),
    ]
