# Generated by Django 4.1 on 2023-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0049_option_commande_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option_commande_intermediaire",
            name="date_transaction",
            field=models.CharField(default=None, max_length=65),
        ),
    ]
