# Generated by Django 4.1 on 2023-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_djaagou_scan",
            "0050_alter_option_commande_intermediaire_date_transaction",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="option_commande",
            name="date_transaction",
            field=models.CharField(default=None, max_length=65),
        ),
    ]
