# Generated by Django 4.1 on 2023-02-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0051_alter_option_commande_date_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_card_social_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_logo", models.CharField(default=None, max_length=255)),
                ("name", models.CharField(max_length=25)),
                ("id_user", models.IntegerField(default=None)),
                ("link", models.CharField(default=None, max_length=80)),
                ("phone_number", models.BigIntegerField(default=None, null=True)),
            ],
        ),
    ]
