# Generated by Django 4.1 on 2023-02-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_djaagou_scan", "0052_business_card_social_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option_commande_intermediaire",
            old_name="id_unknown_user",
            new_name="id_commande",
        ),
    ]
